- name: Deploy Containerized App
  hosts: servers
  become: yes
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      changed_when: false
      ignore_errors: true

    - name: Install Docker (if not present)
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_check.rc != 0

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Application Container
      community.docker.docker_container:
        name: my-app
        image: nginx:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "8091:80"

    - name: Run Custom App from Docker Hub
      community.docker.docker_container:
        name: my-custom-app
        image: dante0293/prikm:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "8093:80"
